import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path

import gen_voice
from gen_captions import generate_captions
from gen_captions import load_model as load_caption_model
from gen_voice import generate_voice, wav_duration
from gen_voice import load_model as load_voice_model

REPO_ROOT = Path(__file__).resolve().parent.parent

RESOLUTION_BY_ASPECT = {
    "1080x1920": "portrait",
    "1080x1080": "square",
    "1920x1080": "landscape",
}

# The repo's shared brand kit (assets/frame.md + assets/fonts/) — not any specific example
# project. Keeping the default theme source independent of video/explainer-01 means deleting
# or heavily editing that example doesn't silently break every future project's default look.
THEME_SOURCE_DEFAULT = "assets"

THEMED_NOTE = (
    "- Design system is pre-seeded: frame.md and assets/fonts/ are already in this project, "
    "copied from the house style (blue-professional preset — cream canvas, cobalt #1e2bfa "
    "accent, Space Grotesk + Inter). Skip Step 2 (design invention) entirely and go straight "
    "from Setup to the storyboard/script step. Every frame's @font-face block must reuse "
    "these exact files verbatim (same family names, same weights, same assets/fonts/ paths) "
    "— do not have individual frames fetch, invent, or substitute a different font; that "
    "mismatch is normally caught and fixed in a later pass, which is pure wasted time here."
)
UNTHEMED_NOTE = "- No design system pre-seeded for this project — Step 2 (design invention) runs normally."

BRIEF_TEMPLATE = """---
workflow: faceless-explainer
flow: automation
storyboard: no
message: "{message}"
destination: {destination}
aspect: {aspect}
language: {language}
length: {length}s
angle: {angle}
---

## Intent

{intent}

## Assets

- audio/{name}.wav — the locked voiceover recording, verbatim, source of truth for pacing.
- audio/{name}-captions.json — word/phrase-level timing for the locked VO.

## Customizations

- VO_MODE: verbatim/locked — narration audio and timing are fixed inputs, not generated by this
  workflow. No TTS step; Step 3.1 is replaced by a manual audio_meta.json built from the existing
  wav + captions.
- GSAP-driven motion per scene (default runtime).

## Notes

- Reel safe zone: keep the caption band and any bottom-anchored content clear of the last
  ~250px of canvas height, and scene content clear of the first ~150px, so platform chrome
  (username, caption bar, action rail) never covers it.
{theme_note}
"""


def first_sentence(text):
    text = text.strip().strip('"').strip()
    match = re.search(r"(?<=[.!?])\s+", text)
    return (text[: match.start()] if match else text).strip()


def build_brief(name, script_text, duration, meta, themed):
    aspect = meta.get("aspect", "1080x1920")
    message = (meta.get("message") or first_sentence(script_text)).replace('"', "'")
    return BRIEF_TEMPLATE.format(
        name=name,
        message=message,
        destination=meta.get("destination", "reels"),
        aspect=aspect,
        language=meta.get("language", "en"),
        length=round(duration),
        angle=meta.get("angle", "concept"),
        intent=meta.get("intent") or f"Explain: {message}",
        theme_note=THEMED_NOTE if themed else UNTHEMED_NOTE,
    )


def init_project(project_dir, aspect):
    resolution = RESOLUTION_BY_ASPECT.get(aspect, "portrait")
    subprocess.run(
        [
            "npx", "hyperframes", "init", str(project_dir),
            "--non-interactive", "--example", "blank",
            "--resolution", resolution,
            "--skill=faceless-explainer",
        ],
        check=True,
    )


def _theme_paths(theme_source, video_out):
    # "assets" (the default) means the repo's shared brand kit at the repo root — frame.md and
    # fonts/ directly, no video/<name> nesting. Any other value is treated as an existing
    # project name, so a batch can reuse a different already-built project's own established
    # look instead of the default (e.g. --theme-source thundering-herd).
    if theme_source == "assets":
        base = REPO_ROOT / "assets"
        return base / "frame.md", base / "fonts"
    base = video_out / theme_source
    return base / "frame.md", base / "assets" / "fonts"


def seed_theme(project_dir, video_out, theme_source):
    if not theme_source:
        return False
    src_frame, src_fonts = _theme_paths(theme_source, video_out)
    if not src_frame.exists():
        return False

    shutil.copy2(src_frame, project_dir / "frame.md")

    if src_fonts.is_dir():
        dst_fonts = project_dir / "assets" / "fonts"
        if dst_fonts.exists():
            shutil.rmtree(dst_fonts)
        shutil.copytree(src_fonts, dst_fonts)

    return True


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Batch-generate voice + captions + a pre-filled BRIEF.md for a folder of reel "
            "scripts, one .txt per video. Each script may have a sibling <name>.meta.json "
            "with overrides: message, intent, destination, aspect, language, angle."
        )
    )
    parser.add_argument("--scripts-dir", required=True, type=Path, help="Directory of .txt narration scripts")
    parser.add_argument("--voice-ref", default=Path("voice_ref.wav"), type=Path)
    parser.add_argument("--audio-out", default=Path("audio"), type=Path)
    parser.add_argument("--video-out", default=Path("video"), type=Path)
    parser.add_argument("--sentences-per-chunk", type=int, default=2)
    parser.add_argument("--silence-gap", type=float, default=gen_voice.SILENCE_GAP_SEC_DEFAULT)
    parser.add_argument("--speed", type=float, default=gen_voice.SPEED_DEFAULT, help="Post-generation tempo multiplier, pitch-preserved (1.0 = off)")
    parser.add_argument("--whisper-model", default="base")
    parser.add_argument("--skip-project-init", action="store_true", help="Only generate audio + captions, skip hyperframes init / BRIEF.md")
    parser.add_argument("--names", help="Comma-separated script stems to process (default: all .txt files in --scripts-dir)")
    parser.add_argument("--force", action="store_true", help="Regenerate audio + captions even if they already exist")
    parser.add_argument(
        "--theme-source",
        default=THEME_SOURCE_DEFAULT,
        help=(
            "Where to copy frame.md + fonts/ from, so new projects reuse a design system "
            "instead of inventing one. Default 'assets' is the repo's shared brand kit "
            "(assets/frame.md + assets/fonts/); pass an existing video/<name>/ project name "
            "to reuse that project's own look instead, or '' to disable."
        ),
    )
    args = parser.parse_args()

    scripts = sorted(args.scripts_dir.glob("*.txt"))
    if args.names:
        wanted = {n.strip() for n in args.names.split(",") if n.strip()}
        scripts = [s for s in scripts if s.stem in wanted]
        missing = wanted - {s.stem for s in scripts}
        if missing:
            raise SystemExit(f"No script found for: {', '.join(sorted(missing))}")
    if not scripts:
        raise SystemExit(f"No .txt scripts found in {args.scripts_dir}")

    print(f"Found {len(scripts)} script(s): {[s.stem for s in scripts]}\n")

    needs_voice = args.force or any(not (args.audio_out / f"{s.stem}.wav").exists() for s in scripts)
    needs_captions = args.force or any(not (args.audio_out / f"{s.stem}-captions.json").exists() for s in scripts)

    voice_model = load_voice_model() if needs_voice else None
    caption_model = load_caption_model(args.whisper_model) if needs_captions else None

    for script_path in scripts:
        name = script_path.stem
        print(f"=== {name} ===")
        text = script_path.read_text().strip()
        meta_path = script_path.with_suffix(".meta.json")
        meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}

        wav_path = args.audio_out / f"{name}.wav"
        if args.force or not wav_path.exists():
            _, duration = generate_voice(voice_model, text, args.voice_ref, wav_path, args.sentences_per_chunk, args.silence_gap, args.speed)
        else:
            duration = wav_duration(wav_path)
            print(f"  {wav_path} already exists — skipping voice generation ({duration:.2f}s)")

        captions_path = args.audio_out / f"{name}-captions.json"
        if args.force or not captions_path.exists():
            generate_captions(caption_model, wav_path, captions_path)
        else:
            print(f"  {captions_path} already exists — skipping transcription")

        if args.skip_project_init:
            continue

        project_dir = args.video_out / name
        hf_marker = project_dir / "hyperframes.json"
        if hf_marker.exists():
            print(f"  {project_dir} already initialized — skipping init/BRIEF.md")
            continue

        aspect = meta.get("aspect", "1080x1920")
        init_project(project_dir, aspect)

        themed = seed_theme(project_dir, args.video_out, args.theme_source)
        if themed:
            source_label = "assets/" if args.theme_source == "assets" else f"video/{args.theme_source}/"
            print(f"  seeded frame.md + fonts from {source_label}")

        brief_path = project_dir / "BRIEF.md"
        brief_path.write_text(build_brief(name, text, duration, meta, themed))
        print(f"  wrote {brief_path}")

    print("\nDone. Each video/<name>/ with a BRIEF.md is ready for the faceless-explainer workflow to author + render.")


if __name__ == "__main__":
    main()
